wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1663539824.077605
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 23
      4: 3.9.13
      5: 0.13.1
      8:
      - 1
      - 4
      - 5
